name: MLFlow-DI-t5-small

on: 
  workflow_dispatch:

env:
  test_model_name: t5-small
  test_sku_type: cpu
  test_trigger_next_model: true
  test_queue: test-northeurope-0
  test_set: huggingface-all
  test_keep_looping: false

jobs:
  deploy-model-job:
    runs-on: ubuntu-latest
    steps:
    - name: check-out-repo-step
      uses: actions/checkout@v3
    - name: azure-login-step
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: pip-install-azure-ai-ml
      run: pip install azure-ai-ml
    - name: pip-install-azureml-core
      run: pip install azureml-core
    - name: pip-install-azureml-mlflow
      run: pip install azureml-mlflow==1.53.0
    
    - name: pip-install-mlflow
      run: pip install mlflow
    - name: pip-install-python-box
      run: pip install python-box 
   
    - name: deploy-model-step
      id: deploy-model-step
      run: python generic_automation.py
      working-directory: tests/src/single_workflow_test
    - name: trigger-next-model-step
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      if: ${{ env.test_trigger_next_model == 'true' && steps.deploy-model-step.outputs.NEXT_MODEL != '' && (success() || failure())}}
      run: gh workflow run ${{ steps.deploy-model-step.outputs.NEXT_MODEL }} --ref ${{ github.ref_name }}
